# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    api_documentation:
        servers:
        -   url: //berichten.zaakonline.nl/
            description: Sandbox server
        info:
            description: |
                Welkom inovator! <br>
                Fijn dat je de tijd en moeite hebt genomen om je te verdiepen in dit component. 

                # Ondersteuning
                Word lid van het slackkanaal [https://zaakonline.slack.com](https://zaakonline.slack.com) voor ondersteuning door het ontwikkel team. En krijg regelmatig updates over de ontwikkelingen op het gebied van de zaakonline componenten.
                
                # Introductie               
                Het berichten component is ontwikkeld voor de gemeente Utrecht en heeft als doel het functionele berichten verkeer te faciliteren. Denk hier bij aan berichten via een email naar een klant waar een, mogelijk, sjabloon in gebruikt wordt
                
                # Common ground en open source
                Om het voor andere partijen zo makkelijk mogenlijk te maken dit component bieden we zo veel mogenlijk informatie openbaar aan.  
                - [datamodel als pdf](/schema/datamodel.pdf)
                - [datamodel als mwb](/schema/datamodel.mwb)
                - [codebase op github](https://github.com/GemeenteUtrecht/berichten)
                - [codebase als zip](https://github.com/GemeenteUtrecht/berichten/archive/conduction.zip)
                - [docker container](https://cloud.docker.com/u/huwelijksplanner/repository/docker/huwelijksplanner/berichten-php)
                - [online demo](http://berichten.demo.zaakonline.nl/)

                # OpenAPI Specification, Cross-Origin Resource Sharing en linked Data
                Deze API is gedocumenteerd in het **OpenAPI format** 
                De API bevat Cross-Origin Resource Sharing (CORS) en is geimplementeerd volgen de [W3C spec](https://www.w3.org/TR/cors/) standaarden. De API staat cross-domain communicatie van de browser toe. Alle responses hebben een "wildcard same-origin" dit maakt ze volledig publiekelijk en toegankelijk voor iedereen. Dat geld voor elke code op elke site.

                # Authenticatie

                Trouwplanner heeft twee vormen van authenticatie:
                  - API Key
                  - OAuth2
                OAuth2 - is een open protocol wat veilige authorizatie regeld op een simpele en  gestandarizeerde manier voor het web, mobile en desktop applicaties.

                <security-definitions />

            version: 0.0.1
            title: 'Berichten API'
            termsOfService: 'http://www.zaakonline.nl/terms/'
            contact:
                name: API Support
                email: support@conduction.nl
                url: https://github.com/ConductionNL/zaakonline
            x-logo:
                url: '/img/vng.svg'
                altText: VNG Realisatie
            license:
                name: EUPL 1.2
                url: 'https://opensource.org/licenses/EUPL-1.2'
        externalDocs:
            description: Find out more in depth information on the working of the zaakonline code base.
            url: 'https://github.com/ConductionNL/zaakonline'
        tags:
              # The general endpoints  
            - name: Bericht
              description: "Een bericht is een stukje informatie wat wordt verstuurd tussen tenminste twee actoren"
            - name: Sjabloon
              description: "Het sjabloon object wordt gebruikt om berichten te standaardiseren   en vorm te geven"
            - name: Applicatie
              description: "De Organisatie wordt gebruikt om standaard configuraties in te regelen"  
            # - name: User
            #   description: "Een gebruiker, of in dit geval een applicatie gebonden aan een JWT token behorende tot een organisatie"
              # Grouping the endopoint  
        x-tagGroups:
            - name: berichten
              tags:
              - Bericht
              - Sjabloon
            - name: Applicatie
              tags:
              - Applicatie
            #   - User
        
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php, Client}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Swagger\SwaggerDecorator:
        #decorates: 'api_platform.swagger.normalizer.documentation'
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments:
            - '@App\Swagger\SwaggerDecorator.inner'
            - '%api_documentation%'
        autoconfigure: false     
    
    # please note that last definitions always *replace* previous ones
    App\Subscriber\TablePrefixSubscriber:
        class: App\Subscriber\TablePrefixSubscriber
        arguments:
            - '%table_prefix%'
        tags: 
            - { name: doctrine.event_subscriber }
  
    # Twig database loader
    App\Twig\Loader\DatabaseLoader:
        tags:
        - { name: twig.loader }            